version: '2'

services:
  mysql:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=rootpwd
    - MYSQL_DATABASE=ds_test
    - MYSQL_USER=testuser
    - MYSQL_PASSWORD=testpwd
    ports:
      - "3306:3306"

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: testpwd
      POSTGRES_USER: testuser
      POSTGRES_DB: ds_test
    ports:
      - "5432:5432"

  mssql:
    image: "microsoft/mssql-server-linux"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "rootpwd"